import { Room } from "@/types";

export const defaultRooms: Room[] = [
  {
    id: "all",
    name: "All",
    icon: "home",
    category: "all",
    isDefault: true,
    image: null,
  },
  {
    id: "living_room",
    name: "Living Room",
    icon: "sofa",
    category: "living",
    isDefault: true,
    image: require("@/assets/images/rooms/livingroom.png"),
  },
  {
    id: "bedroom",
    name: "Bedroom",
    icon: "bed",
    category: "sleeping",
    isDefault: true,
    image: require("@/assets/images/rooms/bedroom.png"),
  },
  {
    id: "kitchen",
    name: "Kitchen",
    icon: "fridge",
    category: "utility",
    isDefault: true,
    image: require("@/assets/images/rooms/kitchen.png"),
  },
  {
    id: "bathroom",
    name: "Bathroom",
    icon: "shower",
    category: "utility",
    isDefault: true,
    image: require("@/assets/images/rooms/bathroom.png"),
  },
  {
    id: "dining_room",
    name: "Dining Room",
    icon: "silverware",
    category: "living",
    isDefault: false,
    image: require("@/assets/images/rooms/livingroom.png"),
  },
  {
    id: "office",
    name: "Office / Study",
    icon: "desk",
    category: "work",
    isDefault: false,
    image: require("@/assets/images/rooms/officeroom.jpg"),
  },
  {
    id: "kids_room",
    name: "Kids Room",
    icon: "teddy-bear",
    category: "sleeping",
    isDefault: false,
    image: require("@/assets/images/rooms/kidsroom.jpg"),
  },
  {
    id: "guest_room",
    name: "Guest Room",
    icon: "bed-double",
    category: "sleeping",
    isDefault: false,
    image: require("@/assets/images/rooms/guestroom.jpg"),
  },
  {
    id: "hallway",
    name: "Hallway / Corridor",
    icon: "door",
    category: "transition",
    isDefault: false,
    image: require("@/assets/images/rooms/balcony.jpg"),
  },
  {
    id: "garage",
    name: "Garage",
    icon: "garage",
    category: "utility",
    isDefault: false,
    image: require("@/assets/images/rooms/garage.jpg"),
  },
  {
    id: "garden",
    name: "Outdoor / Garden",
    icon: "tree",
    category: "outdoor",
    isDefault: false,
    image: require("@/assets/images/rooms/garden.jpg"),
  },
  {
    id: "balcony",
    name: "Balcony / Terrace",
    icon: "balcony",
    category: "outdoor",
    isDefault: false,
    image: require("@/assets/images/rooms/balcony.jpg"),
  }
]